/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FindRouteImport } from './routes/find'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ECodeRouteImport } from './routes/e.$code'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAttendeeRouteImport } from './routes/_authenticated/attendee'
import { Route as AuthenticatedOrganizerIndexRouteImport } from './routes/_authenticated/organizer.index'
import { Route as AuthenticatedOrganizerEventsNewRouteImport } from './routes/_authenticated/organizer.events.new'
import { Route as AuthenticatedOrganizerEventsIdRouteImport } from './routes/_authenticated/organizer.events.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ECodeRoute = ECodeRouteImport.update({
  id: '/e/$code',
  path: '/e/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendeeRoute = AuthenticatedAttendeeRouteImport.update({
  id: '/attendee',
  path: '/attendee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizerIndexRoute =
  AuthenticatedOrganizerIndexRouteImport.update({
    id: '/organizer/',
    path: '/organizer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerEventsNewRoute =
  AuthenticatedOrganizerEventsNewRouteImport.update({
    id: '/organizer/events/new',
    path: '/organizer/events/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerEventsIdRoute =
  AuthenticatedOrganizerEventsIdRouteImport.update({
    id: '/organizer/events/$id',
    path: '/organizer/events/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find': typeof FindRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/attendee': typeof AuthenticatedAttendeeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/e/$code': typeof ECodeRoute
  '/organizer/': typeof AuthenticatedOrganizerIndexRoute
  '/organizer/events/$id': typeof AuthenticatedOrganizerEventsIdRoute
  '/organizer/events/new': typeof AuthenticatedOrganizerEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find': typeof FindRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/attendee': typeof AuthenticatedAttendeeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/e/$code': typeof ECodeRoute
  '/organizer': typeof AuthenticatedOrganizerIndexRoute
  '/organizer/events/$id': typeof AuthenticatedOrganizerEventsIdRoute
  '/organizer/events/new': typeof AuthenticatedOrganizerEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/find': typeof FindRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/attendee': typeof AuthenticatedAttendeeRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/e/$code': typeof ECodeRoute
  '/_authenticated/organizer/': typeof AuthenticatedOrganizerIndexRoute
  '/_authenticated/organizer/events/$id': typeof AuthenticatedOrganizerEventsIdRoute
  '/_authenticated/organizer/events/new': typeof AuthenticatedOrganizerEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/find'
    | '/sitemap.xml'
    | '/attendee'
    | '/onboarding'
    | '/e/$code'
    | '/organizer/'
    | '/organizer/events/$id'
    | '/organizer/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/find'
    | '/sitemap.xml'
    | '/attendee'
    | '/onboarding'
    | '/e/$code'
    | '/organizer'
    | '/organizer/events/$id'
    | '/organizer/events/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/find'
    | '/sitemap.xml'
    | '/_authenticated/attendee'
    | '/_authenticated/onboarding'
    | '/e/$code'
    | '/_authenticated/organizer/'
    | '/_authenticated/organizer/events/$id'
    | '/_authenticated/organizer/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FindRoute: typeof FindRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ECodeRoute: typeof ECodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$code': {
      id: '/e/$code'
      path: '/e/$code'
      fullPath: '/e/$code'
      preLoaderRoute: typeof ECodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendee': {
      id: '/_authenticated/attendee'
      path: '/attendee'
      fullPath: '/attendee'
      preLoaderRoute: typeof AuthenticatedAttendeeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/': {
      id: '/_authenticated/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof AuthenticatedOrganizerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/events/new': {
      id: '/_authenticated/organizer/events/new'
      path: '/organizer/events/new'
      fullPath: '/organizer/events/new'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/events/$id': {
      id: '/_authenticated/organizer/events/$id'
      path: '/organizer/events/$id'
      fullPath: '/organizer/events/$id'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendeeRoute: typeof AuthenticatedAttendeeRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrganizerIndexRoute: typeof AuthenticatedOrganizerIndexRoute
  AuthenticatedOrganizerEventsIdRoute: typeof AuthenticatedOrganizerEventsIdRoute
  AuthenticatedOrganizerEventsNewRoute: typeof AuthenticatedOrganizerEventsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendeeRoute: AuthenticatedAttendeeRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrganizerIndexRoute: AuthenticatedOrganizerIndexRoute,
  AuthenticatedOrganizerEventsIdRoute: AuthenticatedOrganizerEventsIdRoute,
  AuthenticatedOrganizerEventsNewRoute: AuthenticatedOrganizerEventsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FindRoute: FindRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ECodeRoute: ECodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
